import {
	SiJavascript,
	SiTypescript,
	SiReact,
	SiSpring,
	SiHtml5,
	SiCss3,
	SiBootstrap,
	SiPython,
	SiCplusplus,
	SiSharp,
	SiPhp,
	SiRuby,
	SiKotlin,
	SiSwift,
	SiAngular,
	SiEjs,
	SiSvelte,
	SiNextdotjs,
	SiNodedotjs,
	SiExpress,
	SiDjango,
	SiFlask,
	SiMysql,
	SiPostgresql,
	SiMongodb,
	SiFirebase,
	SiGraphql,
	SiDocker,
	SiKubernetes,
	SiGit,
	SiGithub,
	SiGitlab,
	SiBitbucket,
	SiLinux,
	SiApple,
	SiFigma,
	SiAdobephotoshop,
	SiAdobexd,
	SiEclipseide,
	SiIntellijidea,
	SiNetlify,
	SiVercel,
	SiHeroku,
	SiWebpack,
	SiTailwindcss,
	SiJest,
	SiMocha,
	SiCypress,
	SiAew,
	SiGooglecloud,
	SiTensorflow,
	SiPytorch,
	SiOpencv,
	SiKeras,
	SiAntdesign,
	SiElectron,
	SiCapacitor,
	SiFlutter,
	SiAndroid,
	SiIos,
	SiRust,
	SiScala,
	SiPerl,
	SiHaskell,
	SiShell,
	SiRedux,
	SiNpm,
	SiYarn,
	SiJenkins,
	SiTerraform,
	SiAnsible,
	SiCircleci,
	SiTravisci,
	SiCloudflare,
	SiOracle,
	SiRedis,
	SiSqlite,
	SiMariadb,
	SiApachekafka,
	SiRabbitmq,
	SiSolidity,
	SiWeb3Dotjs,
	SiEthereum,
	SiBitcoin,
	SiIpfs,
	SiArduino,
	SiRaspberrypi,
	SiBlender,
	SiThreedotjs,
	SiUnity,
	SiUnrealengine,
	SiVmware,
	SiVirtualbox,
	SiJupyter,
	SiPandas,
	SiNumpy,
	SiScikitlearn,
} from "react-icons/si";

export const icons = {
	js: SiJavascript,
	ts: SiTypescript,
	react: SiReact,
	spring: SiSpring,
	html: SiHtml5,
	css: SiCss3,
	bootstrap: SiBootstrap,
	python: SiPython,
	cpp: SiCplusplus,
	php: SiPhp,
	ruby: SiRuby,
	kotlin: SiKotlin,
	swift: SiSwift,
	angular: SiAngular,
	vue: SiEjs,
	svelte: SiSvelte,
	nextjs: SiNextdotjs,
	nodejs: SiNodedotjs,
	express: SiExpress,
	django: SiDjango,
	flask: SiFlask,
	mysql: SiMysql,
	postgresql: SiPostgresql,
	mongodb: SiMongodb,
	firebase: SiFirebase,
	graphql: SiGraphql,
	docker: SiDocker,
	kubernetes: SiKubernetes,
	git: SiGit,
	github: SiGithub,
	gitlab: SiGitlab,
	bitbucket: SiBitbucket,
	linux: SiLinux,
	apple: SiApple,
	figma: SiFigma,
	photoshop: SiAdobephotoshop,
	adobexd: SiAdobexd,
	eclipse: SiEclipseide,
	intellij: SiIntellijidea,
	netlify: SiNetlify,
	vercel: SiVercel,
	heroku: SiHeroku,
	webpack: SiWebpack,
	tailwindcss: SiTailwindcss,
	redux: SiRedux,
	jest: SiJest,
	mocha: SiMocha,
	cypress: SiCypress,
	aws: SiAew,
	googlecloud: SiGooglecloud,
	tensorflow: SiTensorflow,
	pytorch: SiPytorch,
	opencv: SiOpencv,
	keras: SiKeras,
	antdesign: SiAntdesign,
	electron: SiElectron,
	capacitor: SiCapacitor,
	flutter: SiFlutter,
	unity: SiUnity,
	unreal: SiUnrealengine,
	android: SiAndroid,
	ios: SiIos,
	rust: SiRust,
	scala: SiScala,
	perl: SiPerl,
	haskell: SiHaskell,
	shell: SiShell,
	npm: SiNpm,
	yarn: SiYarn,
	jenkins: SiJenkins,
	terraform: SiTerraform,
	ansible: SiAnsible,
	circleci: SiCircleci,
	travisci: SiTravisci,
	cloudflare: SiCloudflare,
	oracle: SiOracle,
	redis: SiRedis,
	sqlite: SiSqlite,
	mariadb: SiMariadb,
	kafka: SiApachekafka,
	rabbitmq: SiRabbitmq,
	solidity: SiSolidity,
	web3js: SiWeb3Dotjs,
	ethereum: SiEthereum,
	bitcoin: SiBitcoin,
	ipfs: SiIpfs,
	arduino: SiArduino,
	raspberrypi: SiRaspberrypi,
	blender: SiBlender,
	threejs: SiThreedotjs,
	unrealengine: SiUnrealengine,
	vmware: SiVmware,
	virtualbox: SiVirtualbox,
	jupyter: SiJupyter,
	pandas: SiPandas,
	numpy: SiNumpy,
	scikitlearn: SiScikitlearn,
};
